### ISSUE TITLE
Current version is broken, please update to 4.0.5

### ISSUE THREAD

**Issue by fritzh** [shiftkey/chocolatey-beyondcompare#13]
Installing beyondcompare now errors with a 404 - the current version is no longer available from scootersoftware.com. It now needs to be downloaded from http://www.scootersoftware.com/BCompare-4.0.5.19480.exe

**Comment by shiftkey** [comment]
@fritzh oops! Thanks for this, I'll organise a new release today...

**Comment by shiftkey** [comment]
In the queue for moderation https://chocolatey.org/packages/beyondcompare/4.0.5.19480
