### ISSUE TITLE
address feedback raised from review

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/chocolatey-beyondcompare#15]
Shout out to @dtgm for the details and excellent guidance :tada:

> - Please add nuspec iconUrl element. Suggested: 
> https://cdn.rawgit.com/dtgm/chocolatey-packages/df0375a1fab41e47eaef69f758e59591091f6cba/icons/beyondcompare.png

> - Please cleary indicate this software is commercial and provides a trial period of X days with Y limitations (if any).

> - Please add trial to the nuspec tags element.

> - Please include silent uninstaller. 
> File name: tools\chocolateyUninstall.ps1 
> Suggested content:
> ```
> $packageName = 'beyondcompare'
> $packageSearch = "Beyond Compare"
> $installerType = 'exe'
> $silentArgs = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
> $validExitCodes = @(0)
> Get-ItemProperty -Path @(  'HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
> 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*' ) `
> -ErrorAction:SilentlyContinue `
> | Where-Object { $_.DisplayName -like "$packageSearch*" } `
> | ForEach-Object { Uninstall-ChocolateyPackage -PackageName "$packageName" `
> -FileType "$installerType" `
> -SilentArgs "$($silentArgs)" `
> -File "$($_.UninstallString)" `
> -ValidExitCodes $validExitCodes }
> ```
>
> - Please add nuspec licenseUrl element with content set to: http://www.scootersoftware.com/index.php?zz=kb_licensev4
> 
> - Please add nuspec copyright element with content set to:
> © 1996 Scooter Software Inc

**Comment by dtgm** [comment]
:sunglasses: thanks 

markdown in review didn't retain indents ... fixed:

<pre>
$packageName = 'beyondcompare'
$packageSearch = "Beyond Compare"
$installerType = 'exe'
$silentArgs = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
$validExitCodes = @(0)
Get-ItemProperty -Path @('HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
                         'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
                         'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*' ) `
                 -ErrorAction:SilentlyContinue `
| Where-Object { $_.DisplayName -like "$packageSearch*" } `
| ForEach-Object { Uninstall-ChocolateyPackage -PackageName "$packageName" `
                                               -FileType "$installerType" `
                                               -SilentArgs "$($silentArgs)" `
                                               -File "$($_.UninstallString)" `
                                               -ValidExitCodes $validExitCodes }
</pre>

**Comment by shiftkey** [comment]
New package published for moderation.
