### ISSUE TITLE
"You must provide a value expression on the right-hand side of the '-' operator."

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/chocolatey-beyondcompare#29]
Reported via disqus:

```
Z:>choco install beyondcompare -y
Installing the following packages:
beyondcompare
By installing you accept licenses for the packages.

beyondcompare v4.1.3.20814
You must provide a value expression on the right-hand side of the '-' operator.

At C:\ProgramData\chocolatey\lib\beyondcompare\tools\chocolateyInstall.ps1:5 ch

ar:12
+ if ($LCID - <<<< in $german)
+ CategoryInfo : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : ExpectedValueExpression
The install of beyondcompare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\beyondcompare\tools\chocolate
yInstall.ps1'.
See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
- beyondcompare
```

**Comment by shiftkey** [comment]
May be something related to the `-y` - I dunno?

**Comment by michaelray** [comment]
This error occurs when using PowerShell < v3.  The -in operator was added in PSv3 and this is the error you would get when trying to use -in with previous versions of PS.

To remain compatible with PSv2, use -contains instead and swap the operands.

I submitted a pull request to correct this:
https://github.com/shiftkey/chocolatey-beyondcompare/pull/30

**Comment by michaelray** [comment]
Here is a link to info on this:
http://www.computerperformance.co.uk/powershell/powershell3-notin.htm#Troubleshooting_PowerShell_-In_and_-NotIn

**Comment by CADbloke** [comment]
ah, thanks for the explains. My fix on Windows 7 ...

```batchfile
choco install -y powershell -force
```

**Comment by shiftkey** [comment]
Pretty sure we fixed this in #30 which has been published. Please let me know if that's not the case.

**Comment by Flouse** [comment]
after the PowerShell updated, It was Fixed.

**Comment by flcdrg** [comment]
FYI Chocolatey currently requires scripts are PowerShell v3 compatible.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
