### ISSUE TITLE
Remove dependency on Chocolatey

### ISSUE THREAD

**Issue by sumo300** [shiftkey/chocolatey-beyondcompare#40]
Your package forces an install/upgrade of Chocolatey itself and thus can easily break usage of BoxStarter, which requires a dependency on earlier versions of Chocolatey.  Matt keeps advancing the API of Chocolatey and BoxStarter cannot keep up.  Is there a particular reason your package depends on Chocolatey itself?

Once Chocolatey gets downgraded, any package being installed after yours fails with the checksum error that many have been experiencing, including your own BC package.

Steps to reproduce:
1. Install Chocolatey (latest) `iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex`
2. Downgrade Chocolatey `choco upgrade chocolatey --version 0.9.10.3 --allow-downgrade`
3. Install Beyond Compare `choco install beyondcompare`

**Comment by shiftkey** [comment]
> Is there a particular reason your package depends on Chocolatey itself?

We added the checksum requirement because people were complaining about our package failing the checksum requirement that was introduced with 0.10 due to a security issue.

 - https://twitter.com/ferventcoder/status/760892254542102528
 - http://us8.campaign-archive1.com/?u=86a6d80146a0da7f2223712e4&id=f2fe8dbe6b

> Once Chocolatey gets upgraded, any package being installed after yours fails with the checksum error that many have been experiencing, including your own BC package.

Did you mean *downgraded* here?

**Comment by sumo300** [comment]
> We added the checksum requirement because people were complaining about our package failing the checksum requirement that was introduced with 0.10 due to a security issue.

Completely understand why the checksums were required, but is adding a dependency on Chocolatey itself the right solution?  Seems like packages that had no checksum were unlisted until they added them.  Doing so forces an unexpected side-effect of Chocolatey itself being upgraded.  Your package out of quite a few was the only one who did this.  Know of any others?

> Did you mean downgraded here?

Yes, I did.  Good catch!  Will correct.

**Comment by shiftkey** [comment]
> Completely understand why the checksums were required, but is adding a dependency on Chocolatey itself the right solution? 

We chose a specific version of chocolatey because it has inbuilt TLS/SSL support, and we could do away with our code to set this in the script to workaround SSL issues: 

```ps
# This is necessary to avoid Invoke-WebRequest failing with "The request was aborted: Could not create SSL/TLS secure channel."
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

I'll get @flcdrg to confirm this is the case, and see whether he has any thoughts on alternatives.

**Comment by flcdrg** [comment]
Hi Michael, I use BoxStarter too, so I know exactly what you're talking about, having just refreshed a PC a couple of weeks ago and struck the issue that many of my dependant packages haven't been updated to support checksums yet, let alone the compat issues you mention.

My workaround was to put beyondcompare as the last package in [my BoxStarter script](https://gist.github.com/flcdrg/87802af4c92527eb8a30). Not a complete solution as it does mean if you want to re-run the boxstarter script you might need to downgrade chocolatey first.

I guess we've got a couple of options here:

1. Wait for Matt (or someone to submit a PR) to update BoxStarter's internal Chocolatey assembly, so this isn't a problem.
2. Revert back to the old code in our package

I guess it depends on how long it will take for 1 to happen and is that a real blocker for lots of people.

**Comment by sumo300** [comment]
> My workaround was to put beyondcompare as the last package in my BoxStarter script. Not a complete solution as it does mean if you want to re-run the boxstarter script you might need to downgrade chocolatey first.

Definitely an option, but not a solution for us.  Our scripts fail so much (very restrictive configurations and a terrible web proxy to boot) that the BoxStarter scripts need to be able to be run repeatedly until everything installs fully.

**Comment by sumo300** [comment]
Sorry for resurrecting this issue, but this is the only package I'm aware that puts a dependency on Chocolatey itself.  Can this be removed now?  BoxStarter does support the newer version of Chocolatey.

**Comment by flcdrg** [comment]
This package is now maintained in https://github.com/flcdrg/au-packages/tree/master/beyondcompare (so it gets automatically updated using the `au` module).

Closing this issue, but I've raised a similar one to follow up over there.

**Comment by shiftkey** [comment]
@flcdrg cool. I'll update the `README` to point to there and mark this repo as read-only, to prevent further confusion.
